version: '3'
services:
  postgresBB:
    image: postgres:13
    restart: unless-stopped
    container_name: bbDB
    environment:
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
    volumes:
      - ./db/production:/var/lib/postgresql/data
    ports:
      - 127.0.0.1:$POSTGRES_PORT:5432
    networks:
      - blackboard_net
networks:
  blackboard_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.30.0/24     
