version: '3'
services:
  clientportfolio:
    restart: unless-stopped
    container_name: ${DOCKER_PREFIX}clientportfolio
    volumes:
      - ./logs:/logs
    ports:
      - $GUNICORN_PORT:$GUNICORN_PORT
    environment:
      - FLASK_SECRET_KEY=$FLASK_SECRET_KEY
      - BB_DATABASE_HOST=$BB_DATABASE_HOST
      - BB_DATABASE_USER=$BB_DATABASE_USER
      - BB_DATABASE_PASSWORD=$BB_DATABASE_PASSWORD
      - GUNICORN_HOST=clientportfolio
      - GUNICORN_PORT=$GUNICORN_PORT
      - GUNICORN_LOGLEVEL=$GUNICORN_LOGLEVEL
    build: ./src/
    command: /docker-entrypoint.sh
    networks:
      - blackboard_net
networks:
  blackboard_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: $DOCKER_NETWORK_ADDRESS
