#!/bin/bash

# Забираем переменные настройки postgreSQL для поключения 
source ../.env
POSTGRES_URI="postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@localhost:${POSTGRES_PORT}/${POSTGRES_DB}"

#Подключаемся к базе данных устанавливем схемы
psql $POSTGRES_URI?options=-c%20search_path%3D${POSTGRES_SCHEMA}



